nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Preload', 'Fields', 'X-Requested-With', 'X-Bypass-Mock']
        expose_headers: ['Link', 'Content-Type']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': ~
