#!/bin/sh

set -e
set -u

if [ $(id -u) != 0 ]; then
    echo "Running this image as non root is not allowed"
    exit 1
fi

: "${UID:=0}"
: "${GID:=${UID}}"

if [ "$#" = 0 ]; then
    set -- "$(command -v bash 2>/dev/null || command -v sh)" -l
fi

if [ "$UID" != 0 ]; then
    usermod -u "$UID" "app" >/dev/null 2>/dev/null && {
        groupmod -g "$GID" "app" >/dev/null 2>/dev/null ||
        usermod -a -G "$GID" "app" >/dev/null 2>/dev/null
    }

    for path in /var/www/api/var /var/www/api/var/cache /var/www/api/var/log /var/www/api/var/mcp-sessions; do
        mkdir -p "$path"
        chown -R "$UID:$GID" "$path" >/dev/null 2>/dev/null || true
    done

    set -- gosu "${UID}:${GID}" "${@}"
fi

exec "$@"
