<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260430133000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Reconcile Doctrine schema drift for release validation.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER INDEX uniq_7d3656aab7d90e22 RENAME TO UNIQ_7D3656A42ABA0561');
        $this->addSql('ALTER INDEX idx_c53df10d0952fa5 RENAME TO IDX_17FD46C1D0952FA5');
        $this->addSql('ALTER INDEX idx_c53df1054177093 RENAME TO IDX_17FD46C154177093');
        $this->addSql('ALTER INDEX idx_c53df10f1751a23 RENAME TO IDX_17FD46C1F39EBE7A');
        $this->addSql('ALTER INDEX idx_c53df109b6b5fba RENAME TO IDX_17FD46C19B6B5FBA');
        $this->addSql('ALTER TABLE cage_hcm_measure ADD source_task_id VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE cage_hcm_measure ADD source_app_code VARCHAR(64) DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN connected_app.authentication_parameters IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.experiment_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.account_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.synced_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.updated_at IS \'\'');
        $this->addSql('ALTER INDEX idx_8dfd88e54d7b7542 RENAME TO IDX_FAAD74854D7B7542');
        $this->addSql('ALTER INDEX idx_8dfd88e59b6b5fba RENAME TO IDX_FAAD74859B6B5FBA');
        $this->addSql('ALTER TABLE experiment ALTER elabftw_metadata TYPE JSONB');
        $this->addSql('ALTER TABLE home_cage_monitoring ADD lights_on_utc_hour SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE home_cage_monitoring ADD light_duration_hours SMALLINT DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.account_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.user_id IS \'\'');
        $this->addSql('ALTER INDEX idx_llm_provider_credential_account RENAME TO IDX_4AC1D2A99B6B5FBA');
        $this->addSql('ALTER INDEX idx_llm_provider_credential_user RENAME TO IDX_4AC1D2A9A76ED395');
        $this->addSql('ALTER INDEX idx_2801f9480952fa5 RENAME TO IDX_3DD796A8D0952FA5');
        $this->addSql('ALTER TABLE time_series ADD source_task_id VARCHAR(64) DEFAULT NULL');
        $this->addSql('ALTER TABLE time_series ADD source_app_code VARCHAR(64) DEFAULT NULL');
        $this->addSql('CREATE UNIQUE INDEX unique_name_account ON variable (name, account_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX unique_name_account');
        $this->addSql('ALTER TABLE time_series DROP source_app_code');
        $this->addSql('ALTER TABLE time_series DROP source_task_id');
        $this->addSql('ALTER INDEX IDX_3DD796A8D0952FA5 RENAME TO idx_2801f9480952fa5');
        $this->addSql('ALTER INDEX IDX_4AC1D2A9A76ED395 RENAME TO idx_llm_provider_credential_user');
        $this->addSql('ALTER INDEX IDX_4AC1D2A99B6B5FBA RENAME TO idx_llm_provider_credential_account');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.user_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.account_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN llm_provider_credential.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE home_cage_monitoring DROP light_duration_hours');
        $this->addSql('ALTER TABLE home_cage_monitoring DROP lights_on_utc_hour');
        $this->addSql('ALTER TABLE experiment ALTER elabftw_metadata TYPE JSON');
        $this->addSql('ALTER INDEX IDX_FAAD74859B6B5FBA RENAME TO idx_8dfd88e59b6b5fba');
        $this->addSql('ALTER INDEX IDX_FAAD74854D7B7542 RENAME TO idx_8dfd88e54d7b7542');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.synced_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.account_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.experiment_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN connected_resource_link.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN connected_app.authentication_parameters IS \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE cage_hcm_measure DROP source_app_code');
        $this->addSql('ALTER TABLE cage_hcm_measure DROP source_task_id');
        $this->addSql('ALTER INDEX IDX_17FD46C19B6B5FBA RENAME TO idx_c53df109b6b5fba');
        $this->addSql('ALTER INDEX IDX_17FD46C1F39EBE7A RENAME TO idx_c53df10f1751a23');
        $this->addSql('ALTER INDEX IDX_17FD46C154177093 RENAME TO idx_c53df1054177093');
        $this->addSql('ALTER INDEX IDX_17FD46C1D0952FA5 RENAME TO idx_c53df10d0952fa5');
        $this->addSql('ALTER INDEX UNIQ_7D3656A42ABA0561 RENAME TO uniq_7d3656aab7d90e22');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
