import type { FeatureFlagRecord } from './featureFlag.types.ts'

const NOW = '2026-01-20T10:00:00.000Z'

export const featureFlagRegistry: FeatureFlagRecord = {
  'metadatapp-feat.enabled': {
    key: 'metadatapp-feat.enabled',
    label: 'MAPP API Features',
    description: 'Gate all metadata-driven CRUD surfaces backed by MAPP API.',
    category: 'metadatapp-feat',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'non-metadatapp-feat.enabled': {
    key: 'non-metadatapp-feat.enabled',
    label: 'Legacy / Non-MAPP API Features',
    description: 'Gate legacy features not backed by MAPP API.',
    category: 'non-metadatapp-feat',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'atmp.enabled': {
    key: 'atmp.enabled',
    label: 'ATMP Module',
    description: 'Controls ATMP studies navigation, routes, and pages.',
    category: 'atmp',
    environments: ['prod', 'demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },

  'dvc.observatory.enabled': {
    key: 'dvc.observatory.enabled',
    label: 'DVC Observatory Cockpit',
    description: 'Enable the DVC Observatory cockpit and related deep-dive views.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dvc.namVcg.enabled': {
    key: 'dvc.namVcg.enabled',
    label: 'NAM-VCG Workbench',
    description: 'Enable NAM-VCG selection, comparison, and FAIR navigator.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dvc.aiInsights.enabled': {
    key: 'dvc.aiInsights.enabled',
    label: 'DVC AI Insights',
    description: 'Enable AI behavior outputs and narratives.',
    category: 'dvc',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dvc.studyal.welfare.enabled': {
    key: 'dvc.studyal.welfare.enabled',
    label: 'DVC Welfare Alarms',
    description: 'Enable welfare alarms and anomaly explanations.',
    category: 'dvc',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dvc.export.enabled': {
    key: 'dvc.export.enabled',
    label: 'DVC FAIR Exports',
    description: 'Enable exports for VCG bundles and context snapshots.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dvc.circadian.enabled': {
    key: 'dvc.circadian.enabled',
    label: 'DVC Circadian Trace',
    description: 'Enable circadian 24h trace and stability summaries.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'namVcg.meanTrace.enabled': {
    key: 'namVcg.meanTrace.enabled',
    label: 'NAM-VCG Mean Trace',
    description: 'Show target vs VCG mean circadian trace comparison.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'cages.enabled': {
    key: 'cages.enabled',
    label: 'Cages Module',
    description: 'Enable top-level cages list and detail routes.',
    category: 'dvc',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'studyal.agentic': {
    key: 'studyal.agentic',
    label: 'Agentic Science Mode',
    description: 'Autonomous suggestions, plans, and next-step narratives for operators.',
    category: 'studyal',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'studyal.explainability': {
    key: 'studyal.explainability',
    label: 'Explain / Why Panel',
    description: 'Surface causal signal explainers and reasoning trails for decisions.',
    category: 'studyal',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'studyal.virtualControl': {
    key: 'studyal.virtualControl',
    label: 'Virtual Control Advanced Insights',
    description: 'Extra context and automated control hints in the virtual console.',
    category: 'studyal',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'studyal.narrative': {
    key: 'studyal.narrative',
    label: 'Narrative / Story Mode',
    description: 'Opinionated, story-led summaries that highlight impact and human tone.',
    category: 'studyal',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'studyal.timeTravelLab': {
    key: 'studyal.timeTravelLab',
    label: 'Time-Travel Lab',
    description: 'Rewind, branch, and simulate system state safely in-browser.',
    category: 'studyal',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.observatory': {
    key: 'feature.observatory',
    label: 'Observatory Command Center',
    description: 'System-wide visual command center for health, risk, and causal insight.',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.auditLogs': {
    key: 'feature.auditLogs',
    label: 'Audit Logs',
    description: 'System-wide audit trail and resource-level timelines.',
    category: 'feature',
    environments: ['prod', 'demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.future': {
    key: 'feature.future',
    label: 'Future / Unfinished Features',
    description: 'Placeholder surface for components that are still dark but shipping.',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: false,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.connectedApps': {
    key: 'feature.connectedApps',
    label: 'Connected Applications',
    description: 'External integrations management (eLabFTW, OSF, FAIR3R, etc.).',
    category: 'feature',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.connectedApps.deepDive': {
    key: 'feature.connectedApps.deepDive',
    label: 'Connected Apps Deep Dive',
    description: 'Enables advanced visualization of data from external integrations (animals, studies, etc.).',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'timeline.enabled': {
    key: 'timeline.enabled',
    label: 'Assay Timeline',
    description: 'Enable horizontal assay/event timeline tabs on investigation and subject pages.',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'import.enabled': {
    key: 'import.enabled',
    label: 'CSV Import Wizard',
    description: 'Enable staged CSV import workflow (upload, mapping, QC, templates).',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'dataEntry.enabled': {
    key: 'dataEntry.enabled',
    label: 'Spreadsheet Data Entry',
    description: 'Enable spreadsheet-like bulk data entry grid with paste + validation.',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.curateGpt.enabled': {
    key: 'feature.curateGpt.enabled',
    label: 'CurateGPT Curation Copilot',
    description: 'Enable the CurateGPT integration for AI-assisted ontology alignment and curation suggestions.',
    category: 'feature',
    environments: ['demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'feature.curationWorkflow.enabled': {
    key: 'feature.curationWorkflow.enabled',
    label: 'API-Backed Data Curation',
    description: 'Enable the new deep-agent-ready scalable curation workflow powered by MAPP API.',
    category: 'feature',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
  'zefix.enabled': {
    key: 'zefix.enabled',
    label: 'Zefix Module',
    description: 'Enable zebrafish-specific pages: lines, batches, rooms, systems, alerts, and housing management.',
    category: 'zefix',
    environments: ['prod', 'demo', 'local'],
    enabled: true,
    updatedAt: NOW,
    updatedBy: 'System Seed',
  },
}
