<?php

declare(strict_types=1);

namespace App\ConnectedApps\Apps\Cedar\Export;

use App\Entity\CanonicalForm;
use App\Entity\CanonicalFormField;

/**
 * Builds a CEDAR template artifact from a {@see CanonicalForm}, closing the loop
 * opened by the CEDAR import path: a form curated in Metadatapp can be written
 * back to CEDAR via the resource server (`createArtifact` / `updateArtifact`).
 *
 * The output follows the CEDAR template model used by the official
 * `cedar-artifact-rest-mcp` — a JSON-Schema envelope (a Template-typed node, a
 * standard JSON-LD context, `_ui.order`) whose `properties` carry one
 * `TemplateField` node per canonical field. Each field maps the canonical
 * datatype to a CEDAR `inputType` and surfaces permissible values as literal
 * value constraints. The server mints the authoritative identifier, so the
 * top-level id is left null exactly like the import/create flow.
 *
 * @see https://github.com/metadatacenter/cedar-artifact-rest-mcp
 */
final class CanonicalFormCedarTemplateBuilder
{
    private const string SCHEMA_VERSION = '1.6.0';

    /**
     * Standard CEDAR JSON-LD prefix map shared by templates and fields.
     *
     * @var array<string, mixed>
     */
    private const array CONTEXT = [
        'xsd' => 'http://www.w3.org/2001/XMLSchema#',
        'pav' => 'http://purl.org/pav/',
        'oslc' => 'http://open-services.net/ns/core#',
        'schema' => 'http://schema.org/',
        'bibo' => 'http://purl.org/ontology/bibo/',
        'skos' => 'http://www.w3.org/2004/02/skos/core#',
        'rdfs' => 'http://www.w3.org/2000/01/rdf-schema#',
        'schema:name' => ['@type' => 'xsd:string'],
        'schema:description' => ['@type' => 'xsd:string'],
        'pav:createdOn' => ['@type' => 'xsd:dateTime'],
        'pav:createdBy' => ['@type' => '@id'],
        'pav:lastUpdatedOn' => ['@type' => 'xsd:dateTime'],
        'oslc:modifiedBy' => ['@type' => '@id'],
        'skos:notation' => ['@type' => 'xsd:string'],
        'pav:version' => ['@type' => 'xsd:string'],
        'bibo:status' => ['@type' => 'xsd:string'],
    ];

    /**
     * Build the CEDAR template artifact for the given canonical form.
     *
     * @return array<string, mixed>
     */
    public function build(CanonicalForm $form): array
    {
        $properties = [];
        $order = [];
        $propertyLabels = [];
        $propertyDescriptions = [];
        $required = [];

        foreach ($this->orderedFields($form) as $field) {
            $key = $this->propertyKey($field, array_keys($properties));
            $label = '' !== trim($field->getLabel()) ? trim($field->getLabel()) : $key;
            $description = $this->cleanString($field->getDescription());

            $properties[$key] = $this->buildField($label, $description, $field);
            $order[] = $key;
            $propertyLabels[$key] = $label;
            $propertyDescriptions[$key] = $description ?? '';

            if ($field->isRequired()) {
                $required[] = $key;
            }
        }

        $name = '' !== trim($form->getTitle()) ? trim($form->getTitle()) : 'Metadatapp form';

        return [
            '@id' => null,
            '@type' => 'https://schema.metadatacenter.org/core/Template',
            '@context' => self::CONTEXT,
            'type' => 'object',
            'title' => $name . ' template schema',
            'description' => $name . ' template schema generated by Metadatapp',
            'schema:name' => $name,
            'schema:description' => $this->cleanString($form->getDescription()) ?? '',
            'schema:schemaVersion' => self::SCHEMA_VERSION,
            'pav:version' => $form->getVersion(),
            'bibo:status' => 'bibo:draft',
            '_ui' => [
                'order' => $order,
                'propertyLabels' => $propertyLabels,
                'propertyDescriptions' => $propertyDescriptions,
            ],
            'properties' => $properties,
            'required' => $required,
            'additionalProperties' => false,
        ];
    }

    /**
     * Build a single CEDAR TemplateField node.
     *
     * @return array<string, mixed>
     */
    private function buildField(string $label, ?string $description, CanonicalFormField $field): array
    {
        $literals = $this->literals($field);
        $inputType = $this->inputType($field, [] !== $literals);

        $valueConstraints = [
            'requiredValue' => $field->isRequired(),
            'multipleChoice' => false,
        ];
        if ([] !== $literals) {
            $valueConstraints['literals'] = $literals;
        }
        if ('numeric' === $inputType) {
            $valueConstraints['numberType'] = 'xsd:decimal';
            $unit = $this->cleanString($field->getUnitConstraint());
            if (null !== $unit) {
                $valueConstraints['unitOfMeasure'] = $unit;
            }
        }
        if ('temporal' === $inputType) {
            $valueConstraints['temporalType'] = 'xsd:dateTime';
        }

        return [
            '@id' => null,
            '@type' => 'https://schema.metadatacenter.org/core/TemplateField',
            '@context' => self::CONTEXT,
            'type' => 'object',
            'title' => $label . ' field schema',
            'description' => $label . ' field schema generated by Metadatapp',
            'schema:name' => $label,
            'schema:description' => $description ?? '',
            'schema:schemaVersion' => self::SCHEMA_VERSION,
            'pav:version' => '0.0.1',
            'bibo:status' => 'bibo:draft',
            '_ui' => ['inputType' => $inputType],
            '_valueConstraints' => $valueConstraints,
            'properties' => [
                '@value' => ['type' => ['string', 'null']],
                '@type' => ['type' => 'string', 'format' => 'uri'],
            ],
            'required' => ['@value'],
            'additionalProperties' => false,
        ];
    }

    /**
     * Map a canonical datatype to a CEDAR input type. Fields with permissible
     * values become single-choice lists regardless of their declared datatype.
     */
    private function inputType(CanonicalFormField $field, bool $hasLiterals): string
    {
        if ($hasLiterals) {
            return 'radio';
        }

        $datatype = strtolower(trim((string) $field->getDatatype()));

        return match (true) {
            \in_array($datatype, ['int', 'integer', 'number', 'numeric', 'float', 'double', 'decimal', 'long'], true) => 'numeric',
            \in_array($datatype, ['date', 'datetime', 'date-time', 'time', 'timestamp'], true) => 'temporal',
            \in_array($datatype, ['bool', 'boolean'], true) => 'radio',
            'email' === $datatype => 'email',
            \in_array($datatype, ['url', 'uri', 'link'], true) => 'link',
            default => 'textfield',
        };
    }

    /**
     * Permissible values rendered as CEDAR literal value constraints. Booleans
     * without explicit values get the canonical true/false pair.
     *
     * @return list<array{label: string}>
     */
    private function literals(CanonicalFormField $field): array
    {
        $literals = [];
        foreach ($field->getAllowedValues() as $value) {
            $label = $this->literalLabel($value);
            if (null !== $label) {
                $literals[] = ['label' => $label];
            }
        }

        if ([] === $literals && \in_array(strtolower(trim((string) $field->getDatatype())), ['bool', 'boolean'], true)) {
            return [['label' => 'true'], ['label' => 'false']];
        }

        return $literals;
    }

    private function literalLabel(mixed $value): ?string
    {
        if (\is_array($value)) {
            foreach (['label', 'value', 'name'] as $key) {
                if (isset($value[$key]) && \is_scalar($value[$key]) && '' !== trim((string) $value[$key])) {
                    return trim((string) $value[$key]);
                }
            }

            return null;
        }

        if (\is_scalar($value) && '' !== trim((string) $value)) {
            return trim((string) $value);
        }

        return null;
    }

    /**
     * @return list<CanonicalFormField>
     */
    private function orderedFields(CanonicalForm $form): array
    {
        $fields = $form->getFields()->toArray();
        usort($fields, static fn (CanonicalFormField $a, CanonicalFormField $b): int => $a->getOrderIndex() <=> $b->getOrderIndex());

        return $fields;
    }

    /**
     * Derive a JSON-safe, unique property key from the field's local key
     * (CEDAR property keys must be non-empty and distinct within a template).
     *
     * @param list<string> $taken
     */
    private function propertyKey(CanonicalFormField $field, array $taken): string
    {
        $base = preg_replace('/[^A-Za-z0-9_-]+/', '_', trim($field->getLocalKey()));
        $base = trim((string) $base, '_');
        if ('' === $base) {
            $base = 'field';
        }

        $key = $base;
        $suffix = 2;
        while (\in_array($key, $taken, true)) {
            $key = $base . '_' . $suffix;
            ++$suffix;
        }

        return $key;
    }

    private function cleanString(?string $value): ?string
    {
        if (null === $value) {
            return null;
        }

        $value = trim($value);

        return '' === $value ? null : $value;
    }
}
