#!/usr/bin/env python3
"""
generate-declarations.py

Generate machine- and human-readable *repository declarations* from evidence
found in the repo. Each declaration is a Markdown file with a structured YAML
front matter (machine-readable) followed by a narrative body (human-readable),
plus a single machine index at `.well-known/repo-declarations.json`.

Declarations and when they are emitted:

  AI-declaration.md  -> when the repo uses AI (agents, prompts, models, MCP).
  FAIR.md            -> when the repo manages or describes research *data*.
  TRUST.md           -> when the repo does AI *knowledge management* (MCP/RAG,
                        prompt/eval corpora, governed knowledge bases).
  design.md          -> when the repo has a frontend. Hand-authored here, so the
                        generator only validates + indexes it (managed: false).

Other relevant declarations the generator can also emit (opt-in via config or
flags, documented in docs/architecture/repo-declarations.md):
  CITATION.cff, codemeta.json, llms.txt, SBOM.

Design goals
------------
* Deterministic: no timestamps inside generated artifacts, so `--check` is
  stable and CI can fail on drift. Provenance = generator + spec version +
  evidence + content hash.
* Evidence-driven: every claim is backed by a path that exists in the repo.
* Non-destructive: declarations marked `managed: false` are never overwritten.

Usage
-----
  python3 scripts/generate-declarations.py            # write/update files
  python3 scripts/generate-declarations.py --check    # CI: exit 1 on drift
  python3 scripts/generate-declarations.py --list      # show detected signals
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

try:
    import yaml
except ImportError:  # pragma: no cover - dependency guard
    sys.stderr.write(
        "PyYAML is required: pip install pyyaml (or run inside the dev container)\n"
    )
    sys.exit(2)

# ---------------------------------------------------------------------------
# Paths & constants
# ---------------------------------------------------------------------------

# Default target is the repo this script lives in; `--root` overrides it so the
# generator can run against any checked-out repository (e.g. from a central
# reusable CI workflow). All path helpers read REPO_ROOT at call time.
REPO_ROOT = Path(__file__).resolve().parent.parent

GENERATOR = "scripts/generate-declarations.py"
# Bump SPEC_VERSION when the machine-readable shape changes; bump VOCAB_VERSION
# when the wording of the principle framework or capability labels changes.
SPEC_VERSION = 2
VOCAB_VERSION = 1

GENERATED_BANNER = (
    "GENERATED by scripts/generate-declarations.py — do not edit by hand. "
    "Update .declarations.yml or the repo evidence, then re-run "
    "`castor declarations` (or python3 scripts/generate-declarations.py)."
)

# Directories we never treat as evidence sources.
IGNORE_DIRS = {".git", "node_modules", "vendor", "var", "dist", "build", ".venv"}


# ---------------------------------------------------------------------------
# Repo inspection helpers
# ---------------------------------------------------------------------------


def exists(rel: str) -> bool:
    return (REPO_ROOT / rel).exists()


def glob_hits(pattern: str, limit: int = 1) -> list[str]:
    """Return up to `limit` repo-relative paths matching a glob, ignoring noise."""
    hits: list[str] = []
    for p in sorted(REPO_ROOT.glob(pattern)):
        rel = p.relative_to(REPO_ROOT)
        if any(part in IGNORE_DIRS for part in rel.parts):
            continue
        hits.append(str(rel))
        if len(hits) >= limit:
            break
    return hits


def collect_evidence(candidates: list[str]) -> list[str]:
    """Resolve a list of paths/globs to the subset that actually exists.

    Plain paths are kept if present; entries containing glob metacharacters are
    expanded (first match kept) so the evidence list stays short and stable.
    """
    found: list[str] = []
    for cand in candidates:
        if any(ch in cand for ch in "*?[") :
            found.extend(glob_hits(cand, limit=1))
        elif exists(cand):
            found.append(cand)
    # Stable, de-duplicated order.
    return sorted(dict.fromkeys(found))


def load_config() -> dict:
    config_path = REPO_ROOT / ".declarations.yml"
    if config_path.exists():
        return yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    return {}


def detect_license() -> str:
    notice = REPO_ROOT / "NOTICE"
    if notice.exists() and "Affero" in notice.read_text(encoding="utf-8"):
        return "AGPL-3.0-or-later"
    lic = REPO_ROOT / "LICENSE"
    if lic.exists():
        head = lic.read_text(encoding="utf-8", errors="ignore")[:400]
        if "AFFERO" in head.upper():
            return "AGPL-3.0-or-later"
        if "Apache" in head:
            return "Apache-2.0"
        if "MIT" in head:
            return "MIT"
    return "UNLICENSED"


# ---------------------------------------------------------------------------
# Declaration model
# ---------------------------------------------------------------------------


@dataclass
class Declaration:
    key: str
    filename: str
    title: str
    applies_when: str
    # Candidate paths/globs that, when present, justify emitting the file.
    signals: list[str]
    # render(ctx, evidence) -> (frontmatter_extra: dict, body_markdown: str)
    render: Callable[["Context", list[str]], tuple[dict, str]]
    managed: bool = True

    def evidence(self) -> list[str]:
        return collect_evidence(self.signals)


@dataclass
class Context:
    config: dict
    project: dict = field(default_factory=dict)


@dataclass(frozen=True)
class Capability:
    """A single, evidence-backed thing a repo can demonstrate for a principle.

    `label` and `rationale` are owned centrally (the vocabulary), so the same
    capability reads identically in every repo. A capability is only ever
    claimed when at least one of its `signals` exists — no evidence, no claim.
    """

    id: str
    label: str
    rationale: str
    signals: list[str]

    def evidence(self) -> list[str]:
        return collect_evidence(self.signals)


# ---------------------------------------------------------------------------
# Front-matter + file rendering
# ---------------------------------------------------------------------------


def _yaml_block(data: dict) -> str:
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100).rstrip()


def render_managed_file(decl: Declaration, frontmatter_extra: dict, body: str) -> str:
    """Compose `--- frontmatter --- \n body` deterministically."""
    body = body.strip() + "\n"
    body_hash = hashlib.sha256(body.encode("utf-8")).hexdigest()
    front: dict = {
        "_generated": GENERATED_BANNER,
        "declaration": decl.key,
        "title": decl.title,
        "spec_version": SPEC_VERSION,
        "generator": GENERATOR,
        "applies_when": decl.applies_when,
        "status": "active",
        "evidence": decl.evidence(),
    }
    front.update(frontmatter_extra)
    front["content_sha256"] = body_hash
    return f"---\n{_yaml_block(front)}\n---\n\n{body}"


def content_hash_of(path: Path) -> str:
    if not path.exists():
        return ""
    return hashlib.sha256(path.read_bytes()).hexdigest()


# ---------------------------------------------------------------------------
# Renderers — one per declaration
# ---------------------------------------------------------------------------


def render_ai_declaration(ctx: Context, evidence: list[str]) -> tuple[dict, str]:
    ai = ctx.config.get("ai", {}) or {}
    product = ai.get("product_use", [])
    dev = ai.get("development_use", [])
    guards = ai.get("guardrails", [])
    oversight = ai.get("human_oversight", "required")
    training = bool(ai.get("training_on_user_data", False))

    fm = {
        "schema": "https://w3id.org/ai-declaration/v1",
        "ai_use": {
            "in_product": bool(product),
            "in_development": bool(dev),
            "human_oversight": oversight,
            "training_on_user_data": training,
        },
        "models_and_agents": _ai_agent_evidence(),
        "governance": collect_evidence(
            [
                "policies/ai/curation-governance-policy.yaml",
                "policies/ai/sandbox-policy.yaml",
                "docs/architecture/ai-decision-records/*.md",
                "api/config/packages/ai.yaml",
            ]
        ),
    }

    def bullets(items: list[str]) -> str:
        return "\n".join(f"- {x}" for x in items) if items else "- _None declared._"

    body = f"""# AI Declaration

This repository discloses how artificial intelligence is used, both in the
**product** and in the **development** of the codebase. It follows the spirit of
emerging AI-transparency practices and is generated from verifiable repository
evidence; see the front matter for the machine-readable form.

## AI in the product

{bullets(product)}

## AI in development

{bullets(dev)}

## Models, agents & configuration

The following AI-related artifacts were detected in the repository:

{_evidence_list(fm["models_and_agents"]) or "- _None detected._"}

## Governance & guardrails

Human oversight: **{oversight}**. Training on user/customer data:
**{"yes" if training else "no"}**.

{bullets(guards)}

Policy and decision records backing these claims:

{_evidence_list(fm["governance"]) or "- _None detected._"}

## Scope & honesty

This declaration is auto-generated and intentionally conservative: it only
asserts AI usage that is backed by files present in the repository. If you find
an undisclosed use of AI, please open an issue.
"""
    return fm, body


# ---------------------------------------------------------------------------
# Principle vocabularies (version-pinned, owned centrally)
#
# Each principle dimension carries a fixed framework definition (from the
# external standard) plus a GENERIC CORE list of capabilities that match common
# cross-ecosystem conventions (CITATION.cff, LICENSE, prompts/, evals/, ...).
#
# Repository-specific capabilities (RO-Crate templates, MCP wiki pages, a
# particular AI config path) are NOT hardcoded here — they live in
# `.declarations.yml` under `capabilities:` and are merged onto this core by
# `merge_capabilities()`. This keeps the generator repo-agnostic and ready to
# extract into a shared tool. A capability is only ever claimed when its
# evidence exists, so the same vocabulary stays accurate in any repository.
# ---------------------------------------------------------------------------

# dimension -> (short label, name, framework definition)
FAIR_FRAMEWORK: dict[str, tuple[str, str, str]] = {
    "findable": (
        "F",
        "Findable",
        "Data and metadata carry rich, structured, machine-readable descriptors "
        "and globally resolvable identifiers.",
    ),
    "accessible": (
        "A",
        "Accessible",
        "Metadata is retrievable by its identifier over standard, open protocols, "
        "with documented access paths.",
    ),
    "interoperable": (
        "I",
        "Interoperable",
        "Metadata uses shared vocabularies and serializations so it can be "
        "combined with other datasets.",
    ),
    "reusable": (
        "R",
        "Reusable",
        "Data is released with a clear license and provenance so it can be reused "
        "and preserved.",
    ),
}

FAIR_CAPABILITIES: dict[str, list[Capability]] = {
    "findable": [
        # Note: CITATION.cff / codemeta.json are generated by this tool, so they
        # are intentionally not findable-capabilities here (that would be circular
        # and need a two-pass convergence). Citability is advertised via the index.
        Capability("rich-metadata", "JSON-LD structured metadata",
                   "machine-readable descriptors", ["**/*.jsonld"]),
    ],
    "accessible": [
        Capability("documented-access", "Documented access paths",
                   "human-readable access docs", ["README.md", "README.rst", "docs/"]),
        Capability("standard-api", "Programmatic API",
                   "retrieval over an API", ["api/", "openapi.yaml", "openapi.json"]),
    ],
    "interoperable": [
        Capability("json-ld", "JSON-LD serialization",
                   "linked-data interchange format", ["**/*.jsonld"]),
        Capability("ro-crate", "RO-Crate packaging",
                   "community data-packaging standard",
                   ["ro-crate-metadata.json", "**/ro-crate-metadata.json"]),
    ],
    "reusable": [
        Capability("clear-license", "Clear license",
                   "explicit reuse terms", ["LICENSE", "LICENSE.md", "COPYING", "NOTICE"]),
    ],
}

# dimension -> (name, framework definition)
TRUST_FRAMEWORK: dict[str, tuple[str, str]] = {
    "transparency": (
        "Transparency",
        "The sources, prompts, and evaluations that drive behavior are versioned "
        "and inspectable.",
    ),
    "responsibility": (
        "Responsibility",
        "Access and write-back are governed by documented policies and explicit "
        "boundaries.",
    ),
    "user_focus": (
        "User focus",
        "Features map to documented user needs.",
    ),
    "sustainability": (
        "Sustainability",
        "Governance, roadmap, and licensing keep the knowledge base maintainable "
        "and preservable.",
    ),
    "technology": (
        "Technology",
        "The serving stack and safeguards are documented and reproducible.",
    ),
}

TRUST_CAPABILITIES: dict[str, list[Capability]] = {
    "transparency": [
        Capability("versioned-prompts", "Versioned prompts",
                   "inspectable prompt corpus", ["prompts/"]),
        Capability("eval-suite", "Evaluation suite",
                   "behavior is measured", ["evals/", "evaluations/"]),
        Capability("agent-playbook", "Agent playbook",
                   "contribution rules for AI agents", ["AGENTS.md"]),
    ],
    "responsibility": [
        Capability("governance-policy", "Governance policy",
                   "enforced governance", ["policies/"]),
    ],
    "user_focus": [],
    "sustainability": [
        Capability("governance-doc", "Governance model",
                   "maintained over time", ["GOVERNANCE.md"]),
        Capability("roadmap", "Roadmap", "documented direction", ["ROADMAP.md"]),
        Capability("license", "License", "preservation terms", ["LICENSE", "COPYING"]),
    ],
    "technology": [
        Capability("eval-cases", "Evaluation cases",
                   "regression safety net", ["evals/cases/"]),
    ],
}


def _config_capabilities(config: dict, framework: str) -> dict[str, list[dict]]:
    return (config.get("capabilities", {}) or {}).get(framework, {}) or {}


def merge_capabilities(
    core: dict[str, list[Capability]], extra: dict[str, list[dict]]
) -> dict[str, list[Capability]]:
    """Merge config-supplied capabilities onto the generic core, by dimension.

    For each config entry: if its `id` already exists in that dimension, its
    `signals` are unioned onto the core capability (label/rationale overridden
    when provided); otherwise it is appended as a new capability. This is how a
    repo keeps the generic core but points capabilities at its own files —
    without editing the generator.
    """
    result: dict[str, list[Capability]] = {dim: list(caps) for dim, caps in core.items()}
    for dim, items in (extra or {}).items():
        bucket = result.setdefault(dim, [])
        index = {cap.id: i for i, cap in enumerate(bucket)}
        for item in items or []:
            cid = item["id"]
            signals = list(item.get("signals", []))
            if cid in index:
                existing = bucket[index[cid]]
                bucket[index[cid]] = Capability(
                    cid,
                    item.get("label", existing.label),
                    item.get("rationale", existing.rationale),
                    list(dict.fromkeys(existing.signals + signals)),
                )
            else:
                bucket.append(
                    Capability(cid, item.get("label", cid), item.get("rationale", ""), signals)
                )
    return result


def _assess_dimension(caps: list[Capability]) -> tuple[bool, list[dict], list[str]]:
    """Detect which capabilities in a dimension are supported by evidence.

    Returns (supported, capability_entries, flat_evidence).
    """
    entries: list[dict] = []
    flat: list[str] = []
    for cap in caps:
        ev = cap.evidence()
        if not ev:
            continue
        entries.append({"id": cap.id, "label": cap.label, "evidence": ev})
        flat.extend(ev)
    return bool(entries), entries, sorted(dict.fromkeys(flat))


def _render_principle(mark_name: str, definition: str, entries: list[dict],
                      notes: dict) -> str:
    """Compose one principle section from detected capabilities (no hardcoding)."""
    mark = "✅" if entries else "⚠️"
    lines = [f"### {mark} {mark_name}", "", definition, ""]
    if entries:
        for e in entries:
            ev = ", ".join(f"`{p}`" for p in e["evidence"])
            note = notes.get(e["id"])
            suffix = f" — {note}" if note else ""
            lines.append(f"- **{e['label']}** ({ev}){suffix}")
    else:
        lines.append("- _No supporting capability detected yet._")
    return "\n".join(lines) + "\n"


def render_fair(ctx: Context, evidence: list[str]) -> tuple[dict, str]:
    notes = ctx.config.get("capability_notes", {}) or {}
    caps = merge_capabilities(FAIR_CAPABILITIES, _config_capabilities(ctx.config, "fair"))
    fair_fm: dict = {}
    sections: list[str] = []
    for dim, (letter, name, definition) in FAIR_FRAMEWORK.items():
        supported, entries, flat = _assess_dimension(caps.get(dim, []))
        fair_fm[dim] = {"supported": supported, "capabilities": entries}
        sections.append(_render_principle(f"{letter} — {name}", definition, entries, notes))

    fm = {
        "schema": "https://w3id.org/fair/principles/0.1",
        "vocabulary_version": VOCAB_VERSION,
        "fair": fair_fm,
    }

    body = (
        "# FAIR Declaration\n\n"
        "This repository handles research **data** and metadata, so it publishes a FAIR\n"
        "self-assessment against the [FAIR principles](https://www.go-fair.org/fair-principles/)\n"
        "(Findable, Accessible, Interoperable, Reusable). The front matter is the\n"
        "machine-readable form; the sections below are the human narrative. Every claim\n"
        "below is a *capability detected in the repository* and links to its evidence.\n\n"
        "> Auto-generated assessment — `✅` means at least one supporting capability was\n"
        "> detected, `⚠️` means the principle is in scope but nothing was detected yet.\n\n"
        + "\n".join(sections)
        + "\n## Reviewing this assessment\n\n"
        "This is a starting point, not a certificate. Promote `⚠️` items to `✅` by adding\n"
        "the missing capability (identifiers, protocols, vocabularies, license metadata),\n"
        "then re-run the generator.\n"
    )
    return fm, body


def render_trust(ctx: Context, evidence: list[str]) -> tuple[dict, str]:
    notes = ctx.config.get("capability_notes", {}) or {}
    caps = merge_capabilities(TRUST_CAPABILITIES, _config_capabilities(ctx.config, "trust"))
    trust_fm: dict = {}
    sections: list[str] = []
    for dim, (name, definition) in TRUST_FRAMEWORK.items():
        supported, entries, flat = _assess_dimension(caps.get(dim, []))
        trust_fm[dim] = {"supported": supported, "capabilities": entries}
        sections.append(_render_principle(name, definition, entries, notes))

    fm = {
        "schema": "https://doi.org/10.1038/sdata.2020.33",  # TRUST Principles (Lin et al. 2020)
        "vocabulary_version": VOCAB_VERSION,
        "trust": trust_fm,
    }

    body = (
        "# TRUST Declaration\n\n"
        "This repository performs **AI knowledge management**, so it publishes a\n"
        "self-assessment against the\n"
        "[TRUST Principles](https://doi.org/10.1038/sdata.2020.33) for digital repositories\n"
        "(Transparency, Responsibility, User focus, Sustainability, Technology), applied\n"
        "to the AI knowledge base. The front matter is the machine-readable form; every\n"
        "claim below is a *capability detected in the repository*.\n\n"
        "> Auto-generated — `✅` means at least one supporting capability was detected,\n"
        "> `⚠️` means the principle is in scope but nothing was detected yet.\n\n"
        + "\n".join(sections)
        + "\n## Reviewing this assessment\n\n"
        "Strengthen `⚠️` items by adding the relevant safeguard, source, or policy,\n"
        "then re-run the generator.\n"
    )
    return fm, body


# ---------------------------------------------------------------------------
# Evidence helpers used by renderers
# ---------------------------------------------------------------------------


def _ai_agent_evidence() -> list[str]:
    return collect_evidence(
        [
            "AGENTS.md",
            "CLAUDE.md",
            ".claude",
            ".agents",
            ".agent",
            ".deepagents",
            "prompts/system/*.md",
            "prompts/tasks/*.md",
            "api/config/packages/ai.yaml",
            "evals/cases/*.yaml",
        ]
    )


def _evidence_list(paths: list[str]) -> str:
    return "\n".join(f"- `{p}`" for p in paths)


# ---------------------------------------------------------------------------
# Declaration registry
#
# `signals` here are GENERIC trigger signals that decide whether a declaration
# file is emitted at all. Like capabilities, they are repo-agnostic; a repo adds
# its own trigger signals via `.declarations.yml` (declarations.<key>.signals).
# ---------------------------------------------------------------------------


def build_registry() -> list[Declaration]:
    return [
        Declaration(
            key="ai-declaration",
            filename="AI-declaration.md",
            title="AI Declaration",
            applies_when="repository uses AI (agents, prompts, models, or MCP)",
            signals=[
                "AGENTS.md",
                "CLAUDE.md",
                ".claude",
                ".cursor",
                ".github/copilot-instructions.md",
                "prompts",
                "evals",
            ],
            render=render_ai_declaration,
        ),
        Declaration(
            key="fair",
            filename="FAIR.md",
            title="FAIR Declaration",
            applies_when="repository manages or describes research data",
            signals=[
                "**/*.jsonld",
                "ro-crate-metadata.json",
                "**/ro-crate-metadata.json",
                "datapackage.json",
                "**/*.ttl",
                "**/*.rdf",
            ],
            render=render_fair,
        ),
        Declaration(
            key="trust",
            filename="TRUST.md",
            title="TRUST Declaration",
            applies_when="repository performs AI knowledge management (MCP/RAG, "
            "prompt/eval corpora, governed knowledge base)",
            signals=[
                "prompts",
                "evals",
                "mcp.json",
                ".well-known/mcp.json",
            ],
            render=render_trust,
        ),
        Declaration(
            key="design",
            filename="design.md",
            title="Design Declaration",
            applies_when="repository ships a frontend / design system",
            signals=["design.md", "design-tokens.json", "**/*.tsx", "**/*.jsx"],
            # design.md is hand-authored design tokens; never overwrite it.
            render=lambda ctx, ev: ({}, ""),
            managed=False,
        ),
    ]


# ---------------------------------------------------------------------------
# Machine-only metadata: CITATION.cff and codemeta.json
# ---------------------------------------------------------------------------

# SPDX license id -> human name (extend as needed).
_SPDX_NAMES = {
    "AGPL-3.0-or-later": "GNU Affero General Public License v3.0 or later",
    "Apache-2.0": "Apache License 2.0",
    "MIT": "MIT License",
}


def _split_name(person: dict) -> tuple[str, str]:
    """Return (given_names, family_name) from a config author entry."""
    if person.get("given-names") or person.get("family-names"):
        return person.get("given-names", ""), person.get("family-names", "")
    name = (person.get("name") or "").strip()
    if not name:
        return "", ""
    parts = name.split()
    if len(parts) == 1:
        return "", parts[0]
    return " ".join(parts[:-1]), parts[-1]


def detect_languages() -> list[str]:
    langs = []
    if exists("api") or glob_hits("**/*.php"):
        langs.append("PHP")
    if exists("osoma") or glob_hits("**/*.ts") or glob_hits("**/*.tsx"):
        langs.append("TypeScript")
    if glob_hits("scripts/*.py") or glob_hits("**/*.py"):
        langs.append("Python")
    return langs


def build_citation_cff(ctx: Context) -> str:
    """Citation File Format 1.2.0 (https://citation-file-format.github.io/)."""
    p = ctx.project
    authors = []
    for person in ctx.config.get("authors", []) or []:
        given, family = _split_name(person)
        entry: dict = {}
        if given:
            entry["given-names"] = given
        if family:
            entry["family-names"] = family
        if person.get("affiliation"):
            entry["affiliation"] = person["affiliation"]
        if entry:
            authors.append(entry)
    if not authors and p.get("organization"):
        authors.append({"name": p["organization"]})

    cff: dict = {
        "cff-version": "1.2.0",
        "message": "If you use this software, please cite it as below.",
        "title": p.get("name", "Project"),
        "type": "software",
    }
    if p.get("description"):
        cff["abstract"] = " ".join(p["description"].split())
    if authors:
        cff["authors"] = authors
    if p.get("license"):
        cff["license"] = p["license"]
    if p.get("repository"):
        cff["repository-code"] = p["repository"]
    if p.get("homepage"):
        cff["url"] = p["homepage"]
    if p.get("keywords"):
        cff["keywords"] = list(p["keywords"])
    if p.get("version"):
        cff["version"] = str(p["version"])
    if p.get("date_released"):
        cff["date-released"] = str(p["date_released"])

    header = (
        "# GENERATED by scripts/generate-declarations.py — do not edit by hand.\n"
        "# Update .declarations.yml, then re-run `castor declarations`.\n"
    )
    return header + yaml.safe_dump(cff, sort_keys=False, allow_unicode=True, width=100)


def build_codemeta(ctx: Context) -> str:
    """CodeMeta 2.0 JSON-LD software metadata (https://codemeta.github.io/)."""
    p = ctx.project
    authors = []
    for person in ctx.config.get("authors", []) or []:
        given, family = _split_name(person)
        node: dict = {"@type": "Person"}
        if given:
            node["givenName"] = given
        if family:
            node["familyName"] = family
        if person.get("affiliation"):
            node["affiliation"] = {"@type": "Organization", "name": person["affiliation"]}
        authors.append(node)

    doc: dict = {
        "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
        "@type": "SoftwareSourceCode",
        "name": p.get("name"),
    }
    if p.get("description"):
        doc["description"] = " ".join(p["description"].split())
    if p.get("license"):
        doc["license"] = f"https://spdx.org/licenses/{p['license']}"
    if p.get("repository"):
        doc["codeRepository"] = p["repository"]
    if p.get("homepage"):
        doc["url"] = p["homepage"]
    if p.get("keywords"):
        doc["keywords"] = list(p["keywords"])
    if p.get("version"):
        doc["version"] = str(p["version"])
    langs = detect_languages()
    if langs:
        doc["programmingLanguage"] = langs
    if authors:
        doc["author"] = authors
    if p.get("organization"):
        doc["maintainer"] = {"@type": "Organization", "name": p["organization"]}
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Index + llms.txt
# ---------------------------------------------------------------------------


def build_index(
    ctx: Context,
    active: list[tuple[Declaration, list[str]]],
    rendered: dict[str, str],
    extra: list[dict] | None = None,
) -> dict:
    entries = []
    for decl, evidence in active:
        # Hash the content we are about to write (managed) or what is on disk
        # (human-owned), so the index never drifts against freshly-written files.
        if decl.filename in rendered:
            sha = hashlib.sha256(rendered[decl.filename].encode("utf-8")).hexdigest()
        else:
            sha = content_hash_of(REPO_ROOT / decl.filename)
        entries.append(
            {
                "declaration": decl.key,
                "title": decl.title,
                "path": decl.filename,
                "applies_when": decl.applies_when,
                "managed": decl.managed,
                "evidence": evidence,
                "content_sha256": sha,
            }
        )
    for item in extra or []:
        path = item["path"]
        sha = (
            hashlib.sha256(rendered[path].encode("utf-8")).hexdigest()
            if path in rendered
            else content_hash_of(REPO_ROOT / path)
        )
        entries.append({**item, "content_sha256": sha})
    return {
        "$schema": "https://w3id.org/repo-declarations/v1",
        "spec_version": SPEC_VERSION,
        "generator": GENERATOR,
        "project": {
            "name": ctx.project.get("name"),
            "repository": ctx.project.get("repository"),
            "license": ctx.project.get("license"),
        },
        "declarations": entries,
    }


def build_llms_txt(
    ctx: Context,
    active: list[tuple[Declaration, list[str]]],
    extra: list[dict] | None = None,
) -> str:
    name = ctx.project.get("name", "Project")
    desc = (ctx.project.get("description") or "").strip()
    lines = [f"# {name}", ""]
    if desc:
        lines += [f"> {desc}", ""]
    lines += [
        "This file helps LLMs and AI agents discover the repository's machine- and",
        "human-readable declarations.",
        "",
        "## Declarations",
        "",
    ]
    for decl, _ in active:
        lines.append(f"- [{decl.title}](./{decl.filename}): {decl.applies_when}")
    if extra:
        lines += ["", "## Machine metadata", ""]
        for item in extra:
            lines.append(f"- [{item['title']}](./{item['path']}): {item['applies_when']}")
    lines += [
        "",
        "## Index",
        "",
        "- [Machine-readable index](./.well-known/repo-declarations.json)",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def compute_outputs() -> dict[str, str]:
    """Return {repo_relative_path: desired_content} for every managed artifact."""
    config = load_config()
    project = dict(config.get("project", {}) or {})
    project.setdefault("license", detect_license())
    ctx = Context(config=config, project=project)

    # Per-declaration `managed` override from config.
    overrides = config.get("declarations", {}) or {}

    outputs: dict[str, str] = {}
    active: list[tuple[Declaration, list[str]]] = []

    for decl in build_registry():
        ov = overrides.get(decl.key, {}) or {}
        if "managed" in ov:
            decl.managed = bool(ov["managed"])
        # Repos extend the generic trigger signals with their own paths.
        decl.signals = decl.signals + list(ov.get("signals", []) or [])

        evidence = decl.evidence()
        force = ov.get("force")
        applies = force if force is not None else bool(evidence)
        if not applies:
            continue

        active.append((decl, evidence))

        if not decl.managed:
            # Discovered but human-owned: index only, never overwrite.
            continue

        fm_extra, body = decl.render(ctx, evidence)
        outputs[decl.filename] = render_managed_file(decl, fm_extra, body)

    # Machine-only software metadata (emitted when we have a project name).
    extra_index: list[dict] = []
    meta_cfg = config.get("metadata", {}) or {}
    if project.get("name"):
        if meta_cfg.get("citation_cff", True):
            outputs["CITATION.cff"] = build_citation_cff(ctx)
            extra_index.append(
                {
                    "declaration": "citation",
                    "title": "Citation metadata",
                    "path": "CITATION.cff",
                    "applies_when": "repository is citable software",
                    "managed": True,
                    "evidence": collect_evidence(["LICENSE", "README.md"]),
                }
            )
        if meta_cfg.get("codemeta", True):
            outputs["codemeta.json"] = build_codemeta(ctx)
            extra_index.append(
                {
                    "declaration": "codemeta",
                    "title": "CodeMeta software metadata",
                    "path": "codemeta.json",
                    "applies_when": "repository is software with FAIR metadata",
                    "managed": True,
                    "evidence": collect_evidence(["LICENSE", "README.md"]),
                }
            )

    # Machine index + llms.txt.
    outputs[".well-known/repo-declarations.json"] = (
        json.dumps(build_index(ctx, active, outputs, extra_index), indent=2, ensure_ascii=False)
        + "\n"
    )
    outputs["llms.txt"] = build_llms_txt(ctx, active, extra_index)
    return outputs


def cmd_list() -> int:
    config = load_config()
    print("Detected repository declarations:\n")
    overrides = config.get("declarations", {}) or {}
    for decl in build_registry():
        ov = overrides.get(decl.key, {}) or {}
        decl.signals = decl.signals + list(ov.get("signals", []) or [])
        evidence = decl.evidence()
        force = ov.get("force")
        applies = force if force is not None else bool(evidence)
        managed = bool(ov.get("managed", decl.managed))
        flag = "ACTIVE " if applies else "skip   "
        own = "managed" if managed else "human-owned"
        print(f"  [{flag}] {decl.filename:<22} ({own}) — {decl.applies_when}")
        for e in evidence:
            print(f"            · {e}")
    return 0


def cmd_check() -> int:
    outputs = compute_outputs()
    drift = []
    for rel, content in outputs.items():
        path = REPO_ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != content:
            drift.append(rel)
    if drift:
        sys.stderr.write(
            "Repo declarations are out of date. Run "
            "`python3 scripts/generate-declarations.py` and commit:\n"
        )
        for rel in drift:
            sys.stderr.write(f"  - {rel}\n")
        return 1
    print("Repo declarations are up to date.")
    return 0


def cmd_write() -> int:
    outputs = compute_outputs()
    changed = []
    for rel, content in outputs.items():
        path = REPO_ROOT / rel
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        changed.append(rel)
    if changed:
        print("Updated declarations:")
        for rel in changed:
            print(f"  - {rel}")
    else:
        print("Declarations already up to date.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate repository declarations.")
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Target repository root (default: the repo this script lives in).",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="Fail if files are out of date (CI).")
    group.add_argument("--list", action="store_true", help="List detected declarations and exit.")
    args = parser.parse_args(argv)

    if args.root is not None:
        global REPO_ROOT
        REPO_ROOT = args.root.resolve()

    if args.list:
        return cmd_list()
    if args.check:
        return cmd_check()
    return cmd_write()


if __name__ == "__main__":
    raise SystemExit(main())
